exclude: lib
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-ast
    - id: check-json
    - id: check-merge-conflict
    - id: requirements-txt-fixer
  - repo: https://github.com/humitos/mirrors-autoflake
    rev: v1.1
    hooks:
    - id: autoflake
      args: ["-i", "--remove-all-unused-imports"]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
    - id: black
      language_version: python3
      args: ["-l", "99"]
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.12.1
    hooks:
    - id: blacken-docs
      additional_dependencies: [black]
  - repo: https://github.com/asottile/pyupgrade
    rev: v3.10.1
    hooks:
    - id: pyupgrade
  - repo: https://github.com/PyCQA/bandit
    rev: 1.7.5
    hooks:
    - id: bandit
      args: ["-c", "pyproject.toml"]
      additional_dependencies: ["bandit[toml]"]
  - repo: https://github.com/pycqa/pydocstyle
    rev: 6.3.0
    hooks:
    - id: pydocstyle
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.0.286
    hooks:
    - id: ruff
  - repo: https://github.com/jendrikseipp/vulture
    rev: v2.3
    hooks:
    - id: vulture
      args: ["--min-confidence=90", "src", "tests"]
